### ISSUE TITLE
Move app from radix' playground cluster to production cluster

### ISSUE THREAD

**Issue by ErlendHaa** [equinor/vds-slice#88]
Might be useful to do/think about beforehand

- [x] Discuss which branches/environments we want to have (names, resources, how to use, where to store metrics, how many replicas we want)
- [x] Think about versioning strategy. Consider if we would want a client in the future
- [ ] Go through interface and assure it is as expected (to avoid breaking changes in near future). Consider features we know are coming
- [ ] Decide if we want to run E2E/performance tests on schedule
- [ ] Make sure important security points from Threat Modelling are addressed/planned
- [ ] Decide what to do on production images that won't be redeployed for quite some time and will develop security issues due to not-up-to-date dependencies
- [ ] [Rename the repo or at least come up with the name we would be known on Radix](https://github.com/equinor/vds-slice/issues/20)
- [ ] [Discuss across the team which grafana graphs we want to have in place](https://github.com/equinor/vds-slice/issues/123)
- [x] [Nicer root page](https://github.com/equinor/vds-slice/issues/209)
- [x] Give nicer title to our root page. Now it is just "index", we probably want it to be name of our project
- [x] See if our API should/could make it to the official company API list in a distant future
- [x] Add proper logging mechanism for `dev` and `prod` environment

**Comment by achaikou** [comment]
Moved to production.
Snyk is covering security.
